approvedGitRepositories: []

checksumBehavior: throw

defaultSemverRangePrefix: ""

enableImmutableInstalls: true

enableHardenedMode: true

enableScripts: false

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmMinimalAgeGate: 4320

npmPreapprovedPackages:
  - "@grafana/*"

unsafeHttpWhitelist: []

yarnPath: .yarn/releases/yarn-4.17.0.cjs
