services:
  prometheus:
    image: prom/prometheus:v3.14.0@sha256:5ce7540c3c00ef4ab0c9d2c995c6a5b9c421f44b4a115d97a2c7af3b1c21cbb0
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: >
      --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus

  grafana:
    platform: linux/amd64

    depends_on:
      prometheus:
        condition: service_started

    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-13.0.2}
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
