services:
  prometheus:
    image: prom/prometheus:v3.13.1@sha256:3c42b892cf723fa54d2f262c37a0e1f80aa8c8ddb1da7b9b0df9455a35a7f893
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: >
      --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus

  grafana:
    platform: linux/amd64

    depends_on:
      prometheus:
        condition: service_started

    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-13.0.2}
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
