name: Dependabot reviewer
on: pull_request
permissions:
  pull-requests: write
  contents: write
jobs:
  call-workflow-passing-data:
    uses: grafana/security-github-actions/.github/workflows/dependabot-automerge.yaml@main
    with:
      packages-minor-autoupdate: '["@emotion/css","@grafana/aws-sdk","@grafana/data","@grafana/plugin-ui","@grafana/prometheus","@grafana/runtime","@grafana/schema","@grafana/ui","lodash","semver","tslib","github.com/grafana/grafana-aws-sdk","github.com/grafana/grafana-plugin-sdk-go","github.com/grafana/grafana/pkg/promlib","github.com/stretchr/testify"]'
      repository-merge-method: 'squash'

