name: Latest Grafana API compatibility check
on: [pull_request]
permissions: {}

jobs:
  compatibilitycheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build plugin
        run: yarn run build
      - name: Find module.ts or module.tsx
        id: find-module-ts
        run: |
          MODULETS="$(find ./src -type f \( -name "module.ts" -o -name "module.tsx" \) -print -quit)"
          if [ -z "$MODULETS" ]; then
            echo "No module.ts/module.tsx found under ./src" >&2
            exit 1
          fi
          echo "modulets=${MODULETS}" >> $GITHUB_OUTPUT
      - name: Compatibility check
        uses: grafana/plugin-actions/is-compatible@4698961fa64137fcac207108397ebe8a738a33d1 # v1.0.3
        with:
          module: ${{ steps.find-module-ts.outputs.modulets }}
          comment-pr: no
          fail-if-incompatible: yes
